Cash Register/Controllers/CashRegisterController.cs
using System;
using System.Web.Mvc;
using Cash_Register.Contracts;
using Cash_Register.ViewModels;

namespace Cash_Register.Controllers
{
    public class CashRegisterController : Controller
    {
        private readonly DateTime SessionExpiryPeriod = DateTime.Now.AddDays(60);
        private readonly ISalesmanRepository _salesmanRepository;
        private readonly ILocationRepository _locationRepository;
        private readonly ICashRegisterRepository _cashRegisterRepository;

        public CashRegisterController(ISalesmanRepository salesmanRepository, 
            ILocationRepository locationRepository,
            ICashRegisterRepository cashRegisterRepository)
        {
            _salesmanRepository = salesmanRepository;
            _locationRepository = locationRepository;
            _cashRegisterRepository = cashRegisterRepository;
        }

        public ActionResult Index()
        {
            if (Request.Cookies["login"] != null && Request.Cookies["login"].Value == "true" &&
                Request.Cookies["CRLocationEn"] != null && Request.Cookies["CRLocationAr"] != null && Request.Cookies["locationId"] != null)
            {
                ViewBag.CRLocationEn = Request.Cookies["CRLocationEn"].Value;
                ViewBag.CRLocationAr = Server.UrlDecode(Request.Cookies["CRLocationAr"].Value);

                short locationId = short.Parse(Request.Cookies["locationId"].Value);
                ViewBag.Salesmans = _salesmanRepository.GetSalesmans(locationId);
                ViewBag.reserveAmount = _locationRepository.GetReserveAmount(locationId);
                //ViewBag.SerialNo = _cashRegisterRepository.GetSerialNo(DateTime.Now);
                return View();
            }

            return RedirectToAction("Index", "Home");
        }

        public int SaveCashRegister(DateTime date, short salesman, string period, decimal? cheques, decimal? talabat, decimal? deliveroo,
            decimal? online, decimal? knet, decimal? visa, decimal? expense, int? twentykd, int? tenkd, int? fivekd, int? onekd,
            int? halfkd, int? quarterkd, int? hundfils, int? fiftyfils, int? twentyfils, int? tenfils, int? fivefils, decimal? netBalance)
        {
            if (Request.Cookies["locationId"].Value == null)
            {
                return -30;
            }

            var locationId = short.Parse(Request.Cookies["locationId"].Value);
            var shiftType = period == "evening" ? "pm" : "am";

            var shiftCount = new ShiftCount()
            {
                LocationId = locationId,
                ShiftType = shiftType,
                Salesman = salesman,
                StaffDate = date
            };

            var cRegister = new CRegister()
            {
                Oid = _cashRegisterRepository.GetOid(),
                StaffDate = date,
                TransDate = DateTime.Now,
                Cheques = cheques ?? 0,
                Expense = expense ?? 0,
                FiftyFils = fiftyfils ?? 0,
                FiveFils = fivefils ?? 0,
                FiveKd = fivekd ?? 0,
                HalfKd = halfkd ?? 0,
                HundFils = hundfils ?? 0,
                Knet = knet ?? 0,
                LocationId = locationId,
                NetBalance = netBalance ?? 0,
                OneKd = onekd ?? 0,
                Online = online ?? 0,
                ShiftType = shiftType,
                QuarterKd = quarterkd ?? 0,
                Reserve = _locationRepository.GetReserveAmount(locationId),
                Salesman = salesman,
                Talabat = talabat ?? 0,
                Deliveroo = deliveroo ?? 0,
                TenFils = tenfils ?? 0,
                TenKd = tenkd ?? 0,
                TwentyFils = twentyfils ?? 0,
                TwentyKd = twentykd ?? 0,
                Visa = visa ?? 0,
                ShiftCount = _cashRegisterRepository.GetShiftCount(shiftCount),
                IsDeleted = false,
                IsSynced = false,
                SerialNo = _cashRegisterRepository.GetSerialNo(date)
            };

            var result = _cashRegisterRepository.SaveCashRegister(cRegister);

            if (result != 0)
            {
                return result;
            }

            return -1;
        }


        public int UpdateCashRegister(int oid, DateTime date, short salesman, string period, decimal? cheques, decimal? talabat, decimal? deliveroo,
           decimal? online, decimal? knet, decimal? visa, decimal? expense, int? twentykd, int? tenkd, int? fivekd, int? onekd,
           int? halfkd, int? quarterkd, int? hundfils, int? fiftyfils, int? twentyfils, int? tenfils, int? fivefils, decimal? netBalance)
        {
            var locationId = short.Parse(Request.Cookies["locationId"].Value);
            var shiftType = period == "evening" ? "pm" : "am";

            var cRegister = new CRegister()
            {
                Oid = oid,
                Salesman = salesman,
                StaffDate = date,
                TransDate = DateTime.Now,
                Cheques = cheques ?? 0,
                Expense = expense ?? 0,
                FiftyFils = fiftyfils ?? 0,
                FiveFils = fivefils ?? 0,
                FiveKd = fivekd ?? 0,
                HalfKd = halfkd ?? 0,
                HundFils = hundfils ?? 0,
                Knet = knet ?? 0,
                LocationId = locationId,
                NetBalance = netBalance ?? 0,
                OneKd = onekd ?? 0,
                Online = online ?? 0,
                ShiftType = shiftType,
                QuarterKd = quarterkd ?? 0,
                Reserve = _locationRepository.GetReserveAmount(locationId),
                Talabat = talabat ?? 0,
                Deliveroo = deliveroo ?? 0,
                TenFils = tenfils ?? 0,
                TenKd = tenkd ?? 0,
                TwentyFils = twentyfils ?? 0,
                TwentyKd = twentykd ?? 0,
                Visa = visa ?? 0,
                ShiftCount = 1,
                IsDeleted = false,
                IsSynced = false,
                SerialNo = _cashRegisterRepository.GetSerialNo(date)
            };

            var result = _cashRegisterRepository.UpdateCashRegister(cRegister);

            if (result != 0)
            {
                return result;
            }

            return -1;
        }

        public ActionResult Edit(int oid)
        {
            if(Request.Cookies["CRLocationEn"].Value == null || 
                Request.Cookies["CRLocationAr"].Value == null || 
                Request.Cookies["locationId"].Value == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var cRegister = _cashRegisterRepository.GetCashRegister(oid);
            ViewBag.Location = _locationRepository.GetLocation(cRegister.LocationId).NameAr;

            var salesman = _salesmanRepository.GetSalesman(cRegister.Salesman);
            ViewBag.Salesman = salesman.NameAr;
            ViewBag.SalesmanId = salesman.Sman_Cd;

            ViewBag.CRLocationEn = Request.Cookies["CRLocationEn"].Value;
            ViewBag.CRLocationAr = Server.UrlDecode(Request.Cookies["CRLocationAr"].Value);

            short locationId = short.Parse(Request.Cookies["locationId"].Value);
            ViewBag.Salesmans = _salesmanRepository.GetSalesmans(locationId);
            ViewBag.reserveAmount = _locationRepository.GetReserveAmount(locationId);

            return View(cRegister);
        }

        public ActionResult Print(int oid)
        {
            var cRegister = _cashRegisterRepository.GetCashRegister(oid);
            ViewBag.Location = _locationRepository.GetLocation(cRegister.LocationId).NameAr;
            ViewBag.Salesman = _salesmanRepository.GetSalesman(cRegister.Salesman).NameAr;
            return View(cRegister);
        }

        public ActionResult CRRecords(short salesmanOid)
        {
            if (Request.Cookies["CRLocationEn"].Value == null ||
                Request.Cookies["CRLocationAr"].Value == null ||
                Request.Cookies["locationId"].Value == null)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Message = TempData["Message"];
            var records = _cashRegisterRepository.GetSalesmanCashRegister(salesmanOid);
            ViewBag.Salesman = _salesmanRepository.GetSalesman(salesmanOid).NameAr;
            ViewBag.CRLocationAr = Server.UrlDecode(Request.Cookies["CRLocationAr"].Value);
            return View(records);
        }

        public ActionResult Delete(int oid, short salesmanOid)
        {
            var result = _cashRegisterRepository.DeleteCashRegRecord(oid);
            if (result)
                TempData["Message"] = "Record Deleted!";
            else
                TempData["Message"] = "Could not delete the record!";
            return RedirectToAction("CRRecords", new { salesmanOid });
        }
    }
}

Cash Register/Views/CashRegister/CRRecords.cshtml
@model IEnumerable<Cash_Register.ViewModels.CRegister>

@{
    ViewBag.Title = "Records";
}

@if (ViewBag.Message != null)
{
    <div class="row">
        <div class="col-4 text-center mx-auto">
            <div class="alert alert-warning text-center" role="alert">
                @ViewBag.Message
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-11 mx-auto">
        <div class="row">
            <div class="col-6">
                <h4 class="mb-0 pt-1">Cash Register System | نظام كشف الصندوق</h4>
            </div>
            <div class="col-6 text-right">
                <div class="row">
                    <div class="col-9 pt-2">
                        <h6><span class="pl-2">@ViewBag.CRLocationAr</span> | <span class="pr-2">@ViewBag.Salesman</span></h6>
                    </div>
                    <div class="col-3">
                        <Button class="btn btn-primary" onclick="GoBack()">Back</Button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />


<div class="row">
    <div class="col-11">
        <table class="table table-sm table-bordered text-center">
            <tr>
                @*<th>
                        @Html.DisplayNameFor(model => model.Oid)
                    </th>*@
                <th>
                    Transaction Date
                </th>
                <th>
                    Staff Date
                </th>
                <th>
                    Shift Type
                </th>
                <th>
                    Net Balance
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model.OrderByDescending(x => x.TransDate))
            {
                <tr>
                    <td>
                        @item.TransDate.ToString("dd-MM-yyyy hh:mm:ss tt")
                    </td>
                    <td>
                        @item.StaffDate.ToString("dd-MM-yyyy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ShiftType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NetBalance)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "CashRegister", new { oid = item.Oid }, null) 
                        @*@Html.ActionLink("Delete", "Delete", "CashRegister", new { oid = item.Oid, salesmanOid = item.Salesman }, new { onclick = "return confirm('Are you sure you wish to delete this record\\nهل تريد حذف هذا السجل؟?');" }) |*@
                        <a class="text-danger mx-3" href="#" data-toggle="modal" data-target="#exampleModal-@item.Oid">Delete</a> 
                        @Html.ActionLink("Print", "Print", "CashRegister", new { oid = item.Oid }, null)

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-@item.Oid" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Entry : @item.StaffDate.ToString("dd-MM-yyyy") | @item.ShiftType | @Html.DisplayFor(modelItem => item.NetBalance) KD</h5>
                                        <button type="button" class="close pb-0" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true" style="font-size: xxx-large;top: -15px;position: relative;">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-12">
                                                <h3>هل أنت متأكد من حذف؟</h3>
                                                <h4>Delete this record?</h4>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-primary" data-dismiss="modal">No --- لا</button>
                                        @using (Html.BeginForm("Delete", "CashRegister", new { oid = item.Oid, salesmanOid = item.Salesman }))
                                        {
                                            <button type="submit" class="btn btn-danger">Delete --- حذف</button>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>

                    </td>
                </tr>
            }

        </table>
    </div>
</div>



@section scripts {
    <script>
        function GoBack() {
            var link = "@Url.Action("Index", "CashRegister")"
                            window.location.href = link;
        }
    </script>
}

Cash Register/Views/CashRegister/Print.cshtml
@model Cash_Register.ViewModels.CRegister

@{
    ViewBag.Title = "Print";
}

<style>
    @@media print {
        .print {
            display: none;
        }

        body {
            margin: 0 25mm 25mm 0;
        }
    }

    .printableArea h1 {
        font-size: 2rem;
    }
</style>

<div class="row">
    <div class="col-6"><h2></h2></div>
    <div class="col-6">
        <h2 class="text-

right"></h2>
    </div>
</div>

<div class="row">
    <div class="col-12 text-center mb-3

print">

        <div class="row">
            <div class="col-4 mx-auto">
                <div class="row">
                    <div class="col-6">
                        <button onclick="window.print();" class="btn btn-

dark">
                            Print/طباعة
                        </button>
                    </div>
                    <div class="col-6">
                        <Button class="btn btn-primary" onclick="GoBack()">
                            Back To

                            CR
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-5 printableArea"
         id="printableArea">

        <div class="row">
            <div class="col-12">
                <h1>
                    Serial no. :

                    @Model.SerialNo

                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Staff Date :

                    @Model.StaffDate.ToString("dd-MM-yyyy")

                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Print Date :

                    @Model.TransDate.ToString("dd-MM-yyyy | hh: mm:ss tt")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Location :

                    @ViewBag.Location
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Staff :

                    @ViewBag.Salesman
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Shift Type :

                    @Model.ShiftType
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Cheques :

                    @Model.Cheques.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Online :

                    @Model.Online.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Talabat :

                    @Model.Talabat.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Deliveroo :

                    @Model.Deliveroo.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Knet :

                    @Model.Knet.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Visa :

                    @Model.Visa.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    Reserve :

                    @Model.Reserve.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    20Kd :

                    @Model.TwentyKd
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    10Kd :

                    @Model.TenKd
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    5Kd :

                    @Model.FiveKd
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>1Kd : @Model.OneKd</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    1/2Kd :

                    @Model.HalfKd
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    1/4Kd :

                    @Model.QuarterKd
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    100Fils :

                    @Model.HundFils
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    50Fils :

                    @Model.FiftyFils
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    20Fils :

                    @Model.TwentyFils
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    10Fils :

                    @Model.TenFils
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <h1>
                    5Fils :

                    @Model.FiveFils
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h1>
                    Expense :

                    @Model.Expense.ToString("0.000")
                </h1>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <hr />
                <h1>
                    Net Cash :

                    @Model.NetBalance.ToString("0.000")
                </h1>
            </div>
        </div>



    </div>
</div>

@section scripts {
    <script>
        function GoBack() {
            var link = "@Url.Action("Index", "CashRegister")";
            window.location.href = link;
        }
    </script>
}