ImillReports/ViewModels/LocationViewModel.cs
using System.Collections.Generic;
using static ImillReports.Repository.LocationRepository;

namespace ImillReports.ViewModels
{
    public class LocationViewModel
    {
        public List<LocationItem> LocationItems { get; set; }
    }

    public class LocationItem
    {
        public int LocationId { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string ShortName { get; set; }
        public bool IsSelected { get; set; }
        public LocationType Type { get; internal set; }
        public string TypeName { get; internal set; }
    }

    public class LocationGroupItem
    {
        public int LocationId { get; set; }
        public string Name { get; set; }
    }

    public class TaLocation
    {
        public int Oid { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string DeviceCode { get; set; }
    }
}

ImillReports/ViewModels/ShiftViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ImillReports.ViewModels
{
    public class ShiftViewModel
    {
        public int Oid { get; set; }
        public string Code { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public string DisplayText { get; internal set; }
        public int ShiftCode { get; internal set; }
    }
}

ImillReports/Controllers/LocationController.cs
using System.Web.Mvc;
using Newtonsoft.Json;
using ImillReports.Contracts;

namespace ImillReports.Controllers
{
    [Authorize]
    public class LocationController : Controller
    {
        private readonly ILocationRepository _locationRepository;
        public LocationController(ILocationRepository locationRepository) =>
            _locationRepository = locationRepository;

        public LocationController() { }

        public JsonResult GetLocations()
        {
            var locationViewModel = _locationRepository.GetLocations();
            var json = JsonConvert.SerializeObject(locationViewModel.LocationItems);
            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}

ImillReports/Controllers/ManageTimeAttendanceController.cs
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using ImillReports.Contracts;
using System.Collections.Generic;
using System;
using System.Globalization;

namespace ImillReports.Controllers
{
    public class ManageTimeAttendanceController : Controller
    {
        private readonly ITARepository _iTARepository;

        public ManageTimeAttendanceController(ITARepository iTARepository)
        {
            _iTARepository = iTARepository;
        }

        [HttpGet]
        public ActionResult AllocateShiftLocation()
        {
            ViewBag.Employees = _iTARepository.GetEmployees();
            ViewBag.Shifts = _iTARepository.GetShifts();
            ViewBag.Locations = _iTARepository.GetLocations().OrderBy(x => x.NameEn);
            ViewBag.DataSource = _iTARepository.GetEmpAllocations().OrderBy(x => x.EmpId);
            return View();
        }

        [HttpPost]
        public string AllocateShiftLocation(string locations, string shifts, List<int> verifiedIds, string fromDate, string toDate, 
            bool sun, bool mon, bool tues, bool wed, bool thur, bool fri, bool sat)
        {
            var provider = CultureInfo.InvariantCulture;
            var format = "d-M-yyyy";
            var from = (string.IsNullOrEmpty(fromDate) ? DateTime.ParseExact("01-06-2020", format, provider) : DateTime.ParseExact(fromDate, format, provider));
            var to = string.IsNullOrEmpty(toDate) ? DateTime.ParseExact("31-12-9999", format, provider) : DateTime.ParseExact(toDate, format, provider);

            //var source = _iTARepository.GetEmpAllocations();
            //var result = new ContentResult
            //{
            //    Content = JsonConvert.SerializeObject(source),
            //    ContentType = "application/json"
            //};

            return _iTARepository.UpdateEmpAllocations(locations, shifts, verifiedIds, from, to, sun, mon, tues, wed, thur, fri, sat); ;
        }

        [HttpGet]
        public ActionResult Employees()
        {
            ViewBag.DataSource = _iTARepository.GetEmployees().OrderBy(x => x.EmployeeId);
            return View();
        }

        [HttpPost]
        public ContentResult AddEmployee(int empId, string NameEn, string NameAr)
        {
            _iTARepository.AddEmployee(empId, NameEn, NameAr);

            var source = _iTARepository.GetEmployees();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public ContentResult UpdateEmployee(int oid, int empId, string NameEn, string NameAr)
        {
            var response = _iTARepository.UpdateEmployee(oid, empId, NameEn, NameAr);

            // var source = _iTARepository.GetEmployees();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(response),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public ContentResult DeleteEmployees(List<int> verifiedIds)
        {
            _iTARepository.DeleteEmployees(verifiedIds);

            var source = _iTARepository.GetEmployees();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpGet]
        public ActionResult Locations()
        {
            ViewBag.DataSource = _iTARepository.GetLocations();
            return View();
        }

        [HttpPost]
        public ContentResult AddLocation(string deviceCode, string NameEn, string NameAr)
        {
            _iTARepository.AddLocations(deviceCode, NameEn, NameAr);

            var source = _iTARepository.GetLocations();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public ContentResult UpdateLocation(int oid, string deviceCode, string NameEn, string NameAr)
        {
            var response = _iTARepository.UpdateLocation(oid, deviceCode, NameEn, NameAr);

            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(response),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public ContentResult DeleteLocations(List<int> verifiedIds)
        {
            _iTARepository.DeleteLocations(verifiedIds);

            var source = _iTARepository.GetLocations();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpGet]
        public ActionResult Shifts()
        {
            ViewBag.DataSource = _iTARepository.GetShifts();
            return View();
        }

        [HttpPost]
        public ContentResult AddShift(string code, string startTime, string endTime)
        {
            // var test = TimeSpan.Parse(startTime);
            _iTARepository.AddShift(code, TimeSpan.Parse(startTime), TimeSpan.Parse(endTime));

            var source = _iTARepository.GetShifts();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public ContentResult DeleteShifts(List<int> verifiedIds)
        {
            _iTARepository.DeleteShifts(verifiedIds);

            var source = _iTARepository.GetShifts();
            var result = new ContentResult
            {
                Content = JsonConvert.SerializeObject(source),
                ContentType = "application/json"
            };

            return result;
        }

        [HttpPost]
        public string AddAllocation(string fromDate, string toDate, List<int> employees, string shift, string location,
            bool sun, bool mon, bool tues, bool wed, bool thur, bool fri, bool sat)
        {
            var provider = CultureInfo.InvariantCulture;
            var format = "d-M-yyyy";
            var from = (string.IsNullOrEmpty(fromDate) ? DateTime.ParseExact("01-06-2020", format, provider) : DateTime.ParseExact(fromDate, format, provider));
            var to = string.IsNullOrEmpty(toDate) ? DateTime.ParseExact("31-12-9999", format, provider) : DateTime.ParseExact(toDate, format, provider);
            return _iTARepository.AddAllocation(from, to, employees, shift, location, sun, mon, tues, wed, thur, fri, sat);
        }

        [HttpPost]
        public void DeleteAllocations(List<int> verifiedIds)
        {
            _iTARepository.DeleteAllocations(verifiedIds);
        }

        [HttpGet]
        public ActionResult ManageEmployeeLeave()
        {
            ViewBag.Employees = _iTARepository.GetEmployees();
            ViewBag.DataSource = _iTARepository.GetEmployeeLeaves();
            return View();
        }

        [HttpPost]
        public string AddEmployeeLeaves(string fromDate, string toDate, List<int> employees)
        {
            var provider = CultureInfo.InvariantCulture;
            var format = "d-M-yyyy";
            int index = fromDate.IndexOf('-');
            var innerDate = fromDate.Substring(index + 1);

            var from = (string.IsNullOrEmpty(fromDate) ? DateTime.ParseExact("01-06-2020", format, provider) : DateTime.ParseExact(fromDate, format, provider));
            var to = string.IsNullOrEmpty(toDate) ? DateTime.ParseExact("31-12-9999", format, provider) : DateTime.ParseExact(toDate, format, provider);

            return _iTARepository.AddEmployeeLeaves(from, to, employees);
        }

        [HttpPost]
        public void DeleteEmployeeLeaves(List<int> verifiedIds)
        {
            _iTARepository.DeleteEmployeeLeaves(verifiedIds);
        }
    }
}

ImillReports/Views/ManageTimeAttendance/ManageEmployeeLeave.cshtml
@{
    ViewBag.Title = "Manage Employee Leaves";

    List<object> toolbarItems = new List<object>();
    toolbarItems.Add("Search");
    toolbarItems.Add("ExcelExport");
    toolbarItems.Add("ColumnChooser");
    toolbarItems.Add(new { text = "Delete Record(s)", tooltipText = "Delete the record(s)", id = "deleteRec", prefixIcon = "e-delete" });
}

<div class="container-fluid">
    <div id="main">
        <div class="row clearfix">
            <div class="col-12">
                <div class="card">

                    <div class="row p-3">
                        <div class="col-3 emp">
                            @Html.EJS().MultiSelect("employees").ShowDropDownIcon().AllowFiltering(true).Filtering("onEmpFiltering").Value(ViewBag.Employees).Placeholder("Select Employees").DataSource(
                           (IEnumerable<object>)ViewBag.Employees
                           ).Mode(Syncfusion.EJ2.DropDowns.VisualMode.CheckBox).ShowSelectAll(true).SelectAllText("Select All").UnSelectAllText("UnSelect All").Fields(
                           new Syncfusion.EJ2.DropDowns.MultiSelectFieldSettings { Text = "DisplayText", Value = "Oid" }).ActionBegin("onEmpBegin").DataBound("onEmpBound").Render()
                        </div>

                        <div class="col-2">
                            @Html.EJS().DatePicker("fromDate").Format("dd/MMM/yyyy").Value(ViewBag.startDate).Placeholder("From Date").Render()
                        </div>

                        <div class="col-2">
                            @Html.EJS().DatePicker("toDate").Format("dd/MMM/yyyy").Value(ViewBag.endDate).Placeholder("To Date (Optional)").Render()
                        </div>

                        <div class="col-2">
                            <button type="button" class="btn btn-raised bg-black waves-effect waves-light add" onclick="Add()">Add</button>
                        </div>
                    </div>

                </div>

                <div class="card mt-3">
                    <div class="body">

                        @Html.EJS().Grid("Grid").DataSource((IEnumerable<object>)ViewBag.DataSource).AllowResizing(true).AllowExcelExport().ToolbarClick("toolbarClick").Height("400").Width("auto").ShowColumnChooser(true).Columns(col =>
                           {
                               col.Field("IsVerified").Type("checkbox").Width("60").AllowFiltering(false).AllowSorting(false).Add();
                               col.Field("Oid").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Visible(false).IsPrimaryKey(true).ShowInColumnChooser(false).Add();
                               col.Field("EmployeeId").HeaderText("Emp Id").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Filter(new { type = "CheckBox" }).Add();
                               col.Field("NameEn").Visible(false).Width("80").HeaderText("Emp NameEn").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Left).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                               col.Field("NameAr").Width("80").HeaderText("Emp NameAr").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Right).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                               col.Field("StartDate").Width("100").HeaderText("Start Date").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Format(new { type = "dateTime", format = "dd/MMM/yyyy" }).CustomAttributes(new { @class = "customcss" }).Add();
                               col.Field("EndDate").Width("100").HeaderText("End Date").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Format(new { type = "dateTime", format = "dd/MMM/yyyy" }).CustomAttributes(new { @class = "customcss" }).Add();
                           }).AllowPaging(true).AllowSorting(true).AllowFiltering().FilterSettings(filter => filter.Type(Syncfusion.EJ2.Grids.FilterType.Menu)).PageSettings(
                               page =>
                            {
                                page.PageSizes(true); page.PageSize(25);
                            }).Toolbar(toolbarItems).DataBound("dataBound").RowSelected("OnSelected").RowDeselected("OnDeselected").AllowSelection(true).SelectionSettings(select =>
                            select.Type(Syncfusion.EJ2.Grids.SelectionType.Multiple).CheckboxOnly(true)).Render()
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {

    <script>

        var selectedEmployees = [];
        var verificationIds = [];

        function onEmpBegin(e) {
            this.fields = {
                text: 'DisplayText', value: 'Oid', itemCreated: function (e) {
                    var count = 0;
                    if (count === 0) {
                        for (let i = 0; i < e.dataSource.length; i++) {
                            if (e.curData.IsSelected == true)
                                itemEmpSearch(e.curData.Oid); //pass the corresponding value
                        }
                    }
                }
            }
        }

        function itemEmpSearch(e) {
            if (selectedEmployees.indexOf(e) == -1)
                selectedEmployees.push(e);
        }

        function onEmpBound(e) {
            this.value = selectedEmployees;
        }

        function onEmpFiltering(e) {
            var CBObj = document.getElementById("employees").ej2_instances[0];
            if (e.text == '')
                e.updateData(CBObj.dataSource);
            else {
                var query = new ej.data.Query().from('employees').select(['DisplayText', 'Oid']);
                query = (e.text !== '') ? query.where('DisplayText', 'contains', e.text, true) : query;
                e.updateData(CBObj.dataSource, query);
            }
        }

        function OnSelected(args) {
            if (typeof args.data.Oid === 'undefined') {
                verificationIds = [];
                args.data.forEach(function (item, i) {
                    verificationIds.push(item.Oid);
                });
            } else {
                var selectedId = args.data.Oid;
                verificationIds.push(selectedId);
            }
        }

        function OnDeselected(args) {
            if (args.row.length === 0) {
            } else {
                if (args.row.length > 1) {
                    verificationIds = [];
                } else {
                    var deselectedId = +(args.row[0].cells[1].innerHTML);
                    verificationIds.some(function (item, i) {
                        if (item === deselectedId) {
                            verificationIds.splice(i, 1);
                        }
                    });
                }
            }
        }

        function dataBound(args) {
            // this.autoFitColumns(['EmpId', 'EmpName', 'EmpNameAr', 'Location', 'LocationAr', 'ShiftCode', 'ShiftName', 'StartTime', 'EndTime', 'FromDate', 'ToDate']);
        }

        function toolbarClick(args) {
            var gridObj = document.getElementById("Grid").ej2_instances[0];
            if (args.item.id === 'Grid_excelexport') {
                var excelExportProperties = {
                    fileName: "EmployeeLeaves.xlsx"
                };
                gridObj.excelExport(excelExportProperties);
            }

            if (args.item.id == 'deleteRec') {

            if (verificationIds.length === 0) {
                alert("Select Employee!");
            } else {
                $.ajax({
                    type: 'POST',
                    data: {
                        verifiedIds: verificationIds
                    },
                    url: '@Url.Action("DeleteEmployeeLeaves", "ManageTimeAttendance")',
                    success: function () {
                        verificationIds = [];
                        window.location.reload();
                },
                    error: function (ex) {

                    }
                });

            }
            }
        }

        function Add() {
            var empObj = document.getElementById('employees').ej2_instances[0].value; // MultiSelect Instance of ocations
            var fromDateObj = document.getElementById('fromDate').ej2_instances[0].value;
            var toDateObj = document.getElementById('toDate').ej2_instances[0].value;

            if (empObj.length < 1) {
                alert("Please Select Employee.");
            }
            else if (fromDateObj === null || toDateObj === null) {
                alert("Add Start Date And End Date.");
            } else {

                var sd = new Date(fromDateObj);
                var from = sd.getDate().toString() + '-' + (sd.getMonth() + 1).toString() + '-' + sd.getFullYear().toString();

                var ed = toDateObj !== null ? new Date(toDateObj) : null
                if (toDateObj !== null) {
                    ed.setMonth(ed.getMonth());
                }

                $.ajax({
                    type: 'POST',
                    data: {
                        employees: empObj,
                        fromDate: from,
                        toDate: toDateObj !== null
                            ? ed.getDate().toString() + '-' + (ed.getMonth() + 1).toString() + '-' + ed.getFullYear().toString()
                            : toDateObj
                    },
                    url: '@Url.Action("AddEmployeeLeaves", "ManageTimeAttendance")',
                    success: function (response) {
                        alert(response);
                        window.location.reload();
                    },
                    error: function (ex) {
                        alert('Error Allocation : ', ex);
                    }
                });
            }
        }

    </script>

}