ImillReports/Controllers/SalesReportController.cs
using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Syncfusion.XlsIO;
using ImillReports.Models;
using System.Configuration;
using ImillReports.Contracts;
using ImillReports.ViewModels;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using Syncfusion.EJ2.QueryBuilder;
using System.Web.Script.Serialization;

namespace ImillReports.Controllers
{
    [Authorize]
    public class SalesReportController : Controller
    {
        private readonly ISalesReportRepository _salesReportRepository;
        private readonly ILocationRepository _locationRepository;
        private readonly IBaseUnitRepository _baseUnitRepository;
        private readonly IVoucherTypesRepository _voucherTypesRepository;
        private readonly IProductRepository _productRepository;
        private readonly IBaseRepository _baseRepository;
        public SalesReportController(
            ISalesReportRepository salesReportRepository,
            ILocationRepository locationRepository,
            IBaseUnitRepository baseUnitRepository,
            IProductRepository productRepository,
            IBaseRepository baseRepository,
            IVoucherTypesRepository voucherTypesRepository)
        {
            _salesReportRepository = salesReportRepository;
            _locationRepository = locationRepository;
            _baseUnitRepository = baseUnitRepository;
            _voucherTypesRepository = voucherTypesRepository;
            _productRepository = productRepository;
            _baseRepository = baseRepository;
        }

        private readonly string PageName = "SalesDetailReport";
        // jsuts che
        public SalesReportController() { }

        #region Sales Report

        [HttpGet]
        public ActionResult Index(DateTime? fromDate, DateTime? toDate, string[] locationStringArray, string[] voucherTypeStringArray)
        {
            if (fromDate == null)
            {
                var fDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 03, 00, 00);
                fromDate = fDate;
                ViewBag.startDate = fDate;
            }

            if (toDate == null)
            {
                var tDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 02, 59, 00).AddDays(1);
                toDate = tDate;
                ViewBag.endDate = tDate;
            }

            ViewBag.startDate = fromDate;
            ViewBag.endDate = toDate;
            ViewBag.validation = "false";

            if (toDate < fromDate) ViewBag.validation = "true";

            var locations = _locationRepository.GetLocations().LocationItems;

            var locationArray = new List<int>();
            if (locationStringArray != null)
            {
                locationArray.AddRange(from item in locationStringArray select int.Parse(item));
                foreach (var currentLocation in
                    from location in locations
                    from id in locationArray
                    where location.LocationId == id
                    select location)
                {
                    currentLocation.IsSelected = true;
                }
            }

            ViewBag.locations = locations.OrderBy(x => x.Name);
            ViewBag.locationVal = new string[] { "" };

            //var enumData = from LocationType e in Enum.GetValues(typeof(LocationType))
            //               select new
            //               {
            //                   Id = (int)e,
            //                   Name = e.ToString()
            //               };

            //var selectEnumData = new SelectList(enumData, "Id", "Name");

            //var locationGroupItems = new List<LocationGroupItem>();

            //foreach (var item in selectEnumData)
            //{
            //    var locationGroupItem = new LocationGroupItem
            //    {
            //        LocationId = int.Parse(item.Value),
            //        Name = item.Text
            //    };

            //    locationGroupItems.Add(locationGroupItem);
            //}


            var voucherTypes = _voucherTypesRepository.GetSalesVoucherTypes().VoucherTypeItems;
            var voucherTypesArray = new List<int>();
            if (voucherTypeStringArray != null)
            {
                voucherTypesArray.AddRange(from item in voucherTypeStringArray select int.Parse(item));
                foreach (var currentVoucherType in
                    from types in voucherTypes
                    from id in voucherTypesArray
                    where types.Voucher_Type == id
                    select types)
                {
                    currentVoucherType.IsSelected = true;
                }
            }

            ViewBag.voucherTypes = voucherTypes.OrderBy(x => x.L_Voucher_Name);
            ViewBag.voucherTypesVal = new string[] { "" };


            if (fromDate.Value.Date == DateTime.Now.Date || fromDate == null)
            {
                var srs = new List<SalesReportItem>();
                var sr = new SalesReportItem
                {
                    Amount = 0,
                    AmountRecieved = 0,
                    BaseQuantity = 0,
                    BaseUnit = "",
                    Cash = 0,
                    CreditCard = 0,
                    CreditCardType = "",
                    CustomerName = "",
                    CustomerNameAr = "",
                    Date = DateTime.Now,
                    Discount = 0,
                    GroupCD = 0,
                    InvDateTime = DateTime.Now,
                    InvoiceNumber = 0,
                    Knet = 0,
                    Location = "",
                    LocationId = 0,
                    NetAmount = 0,
                    ProductNameAr = "",
                    ProductNameEn = "",
                    Salesman = "",
                    SellQuantity = 0,
                    SellUnit = "",
                    UnitPrice = 0,
                    Voucher = "",
                    VoucherId = 0
                };

                srs.Add(sr);

                ViewBag.DataSource = srs;
                return View();
            }

            var locationsString = locationStringArray != null && locationStringArray.Length > 0 ? string.Join(",", locationStringArray) : "";
            var voucherTypeString = voucherTypeStringArray != null && voucherTypeStringArray.Length > 0 ? string.Join(",", voucherTypeStringArray) : "";

            var salesReportViewModel = _salesReportRepository.GetSalesReport(fromDate, toDate, locationsString, voucherTypeString);
            ViewBag.DataSource = salesReportViewModel.SalesReportItems;

            return View();
        }

        [HttpGet]
        public ActionResult SalesDetailReport(DateTime? fromDate, DateTime? toDate, string[] locationStringArray,
            string[] voucherTypeStringArray, bool? _, string[] productStringArray, string[] _1, JsonResult _2)
        {

            if (fromDate == null)
            {
                var fDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 03, 00, 00);
                fromDate = fDate;
                ViewBag.startDate = fDate;
            }

            if (toDate == null)
            {
                var tDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 02, 59, 00).AddDays(1);
                toDate = tDate;
                ViewBag.endDate = tDate;
            }

            ViewBag.startDate = fromDate;
            ViewBag.endDate = toDate;
            ViewBag.validation = "false";

            if (toDate < fromDate)
            {
                ViewBag.validation = "true";
            }

            var locations = _locationRepository.GetLocations().LocationItems;

            var locationArray = new List<int>();
            if (locationStringArray != null)
            {
                locationArray.AddRange(from item in locationStringArray select int.Parse(item));
                foreach (var currentLocation in
                    from location in locations
                    from id in locationArray
                    where location.LocationId == id
                    select location)
                {
                    currentLocation.IsSelected = true;
                }
            }

            ViewBag.locations = locations.OrderBy(x => x.Name);
            ViewBag.locationVal = new string[] { "" };

            //var enumData = from LocationType e in Enum.GetValues(typeof(LocationType))
            //               select new
            //               {
            //                   Id = (int)e,
            //                   Name = e.ToString()
            //               };

            //var selectEnumData = new SelectList(enumData, "Id", "Name");

            //var locationGroupItems = new List<LocationGroupItem>();

            //foreach (var item in selectEnumData)
            //{
            //    var locationGroupItem = new LocationGroupItem
            //    {
            //        LocationId = int.Parse(item.Value),
            //        Name = item.Text
            //    };

            //    locationGroupItems.Add(locationGroupItem);
            //}

            //ViewBag.locations = locationGroupItems;
            //ViewBag.locationVal = new string[] { "" };


            var voucherTypes = _voucherTypesRepository.GetSalesVoucherTypes().VoucherTypeItems;
            var voucherTypesArray = new List<int>();
            if (voucherTypeStringArray != null)
            {
                voucherTypesArray.AddRange(from item in voucherTypeStringArray select int.Parse(item));
                foreach (var currentVoucherType in
                    from types in voucherTypes
                    from id in voucherTypesArray
                    where types.Voucher_Type == id
                    select types)
                {

ImillReports/Views/SalesReport/DailyConsumption.cshtml
@{
    ViewBag.Title = "Daily Consumption Report";
    ViewBag.SubTitle = "Analyse the total quantity of each item delivered";
    var test = ViewBag.DataSource;
    var test2 = "";
}

<style>
    .e-grid .e-rowcell.customcss {
        font-size: 11px;
    }

    .e-grid .e-headercell.customcss {
        font-size: 11px;
    }

    .e-grid .e-summaryrow .e-summarycell, .e-grid .e-summaryrow .e-templatecell {
        font-size: 11px;
    }

    .e-headertext {
        font-size: 11px;
    }
</style>

<div class="container-fluid">
    @if (ViewBag.validation == "true")
    {
        <div class="row">
            <div class="col-12">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    Start Date is Greater then End Date
                </div>
            </div>
        </div>
    }
    <div class="row clearfix">
        <div class="col-12">
            <div class="card">
                @using (Html.BeginForm("DailyConsumption", "SalesReport", FormMethod.Get))
                {
                <div class="row p-3">
                    <div class="col-3">
                        @Html.EJS().DateTimePicker("fromDate").Format("dd/MMM/yyyy hh:mm a").Value(ViewBag.startDate).Render()
                    </div>

                    <div class="col-3">
                        @Html.EJS().DateTimePicker("toDate").Format("dd/MMM/yyyy hh:mm a").Value(ViewBag.endDate).Render()
                    </div>

                    <div class="col-2">
                        <button type="submit" class="btn btn-raised bg-black waves-effect waves-light getRecords">Get Records</button>
                    </div>
                </div>
                }
            </div>
            <div class="card mt-3">
                <div class="body">

                    @Html.EJS().Grid("Grid").DataSource((IEnumerable<object>)ViewBag.DataSource).AllowResizing(true).AllowExcelExport().ToolbarClick("toolbarClick").Height("600").Width("auto").ShowColumnChooser(true).Columns(col =>
               {
                   col.Field("ItemNameEn").HeaderText("Item NameEn").Width("80").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("ItemNameAr").HeaderText("Item NameAr").Width("150").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("BaseUnit").Visible(false).HeaderText("Unit").Width("150").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("TotalQty").HeaderText("Total Quantity").Width("80").Format("N3").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Filter(new { type = "CheckBox" }).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("TotalBranchQty").HeaderText("Branch Quantity").Width("80").Format("N3").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("CreditQty").HeaderText("Credit Quantity").Width("80").Format("N3").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).CustomAttributes(new { @class = "customcss" }).Add();
                   col.Field("CashQty").HeaderText("Cash Quantity").Width("80").Format("N3").TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).CustomAttributes(new { @class = "customcss" }).Add();
               }).AllowPaging(true).AllowSorting(true).AllowFiltering().FilterSettings(filter => filter.Type(Syncfusion.EJ2.Grids.FilterType.Menu)).PageSettings(
                   page => { page.PageSizes(true); page.PageSize(25); }).Toolbar(new List<string>() { "Search", "Print", "ExcelExport", "ColumnChooser" }).Aggregates(agg =>
                   {
                       agg.Columns(new List<Syncfusion.EJ2.Grids.GridAggregateColumn>() {
                           new Syncfusion.EJ2.Grids.GridAggregateColumn() {
                               Field = "TotalQty", Format= "N3", Type = "Sum", FooterTemplate = "${Sum}"
                           }, new Syncfusion.EJ2.Grids.GridAggregateColumn() {
                               Field = "TotalBranchQty", Format= "N3", Type = "Sum", FooterTemplate = "${Sum}"
                           }, new Syncfusion.EJ2.Grids.GridAggregateColumn() {
                               Field = "CreditQty", Format= "N3", Type = "Sum", FooterTemplate = "${Sum}"
                           }, new Syncfusion.EJ2.Grids.GridAggregateColumn() {
                               Field = "CashQty", Format= "N3", Type = "Sum", FooterTemplate = "${Sum}"
                           }
                       }).Add();
                   }).DataBound("dataBound").Load("load").Render()


                </div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function dataBound(args) {
            this.autoFitColumns(['ItemNameEn', 'ItemNameAr', 'TotalQty', 'TotalBranchQty', 'CreditQty', 'CashQty', 'BaseUnit']);
        }

        function load() {
            var grid = document.getElementById('Grid').ej2_instances[0];
            var rowHeight = grid.getRowHeight();  //height of the each row
            var gridHeight = grid.height;  //grid height
            var pageSize = grid.pageSettings.pageSize;   //initial page size
            var pageResize = 25; //new page size is obtained here
            grid.pageSettings.pageSize = pageSize + Math.round(pageResize);
        }

        function toolbarClick(args) {
            var gridObj = document.getElementById("Grid").ej2_instances[0];
            if (args.item.id === 'Grid_excelexport') {
                var excelExportProperties = {
                    fileName: "DailyConsumption.xlsx"
                };
                gridObj.excelExport(excelExportProperties);
            }
        }

    </script>
}